### ISSUE TITLE
Lab 2 Completion Tracking

### ISSUE THREAD

**Issue by deargle** [alexqaddourah/msbx5500-spring-2020#7]
* [ ] Do both "Midterm 1" and "Midterm 2" at least once
* [ ] Skim through entire book
* [x] Apply to at least one job by the end of the week
  * you already told me you finished this one, awesome!

**Comment by deargle** [comment]
closing this in favor of github "projects" board
